spring:
  redis:
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/flower?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 100
      max-wait: 60000
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  rabbitmq:
    host: localhost
    port: 5672
    username: sevenlion
    password: sevenlion
    virtual-host: /
feign:
  sentinel:
    enabled: true